# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xl/projects/autodrive/autodrive-vision

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xl/projects/autodrive/autodrive-vision

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/xl/projects/autodrive/autodrive-vision/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xl/projects/autodrive/autodrive-vision/CMakeFiles /home/xl/projects/autodrive/autodrive-vision/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xl/projects/autodrive/autodrive-vision/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named advision

# Build rule for target.
advision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 advision
.PHONY : advision

# fast build rule for target.
advision/fast:
	$(MAKE) -f src/CMakeFiles/advision.dir/build.make src/CMakeFiles/advision.dir/build
.PHONY : advision/fast

#=============================================================================
# Target rules for targets named vision

# Build rule for target.
vision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vision
.PHONY : vision

# fast build rule for target.
vision/fast:
	$(MAKE) -f src/CMakeFiles/vision.dir/build.make src/CMakeFiles/vision.dir/build
.PHONY : vision/fast

#=============================================================================
# Target rules for targets named icsneoc

# Build rule for target.
icsneoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icsneoc
.PHONY : icsneoc

# fast build rule for target.
icsneoc/fast:
	$(MAKE) -f icsneo/CMakeFiles/icsneoc.dir/build.make icsneo/CMakeFiles/icsneoc.dir/build
.PHONY : icsneoc/fast

#=============================================================================
# Target rules for targets named icsneocpp

# Build rule for target.
icsneocpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icsneocpp
.PHONY : icsneocpp

# fast build rule for target.
icsneocpp/fast:
	$(MAKE) -f icsneo/CMakeFiles/icsneocpp.dir/build.make icsneo/CMakeFiles/icsneocpp.dir/build
.PHONY : icsneocpp/fast

#=============================================================================
# Target rules for targets named icsneolegacy

# Build rule for target.
icsneolegacy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icsneolegacy
.PHONY : icsneolegacy

# fast build rule for target.
icsneolegacy/fast:
	$(MAKE) -f icsneo/CMakeFiles/icsneolegacy.dir/build.make icsneo/CMakeFiles/icsneolegacy.dir/build
.PHONY : icsneolegacy/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f icsneo/third-party/libftdi/CMakeFiles/dist.dir/build.make icsneo/third-party/libftdi/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named ftdi1-static

# Build rule for target.
ftdi1-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ftdi1-static
.PHONY : ftdi1-static

# fast build rule for target.
ftdi1-static/fast:
	$(MAKE) -f icsneo/third-party/libftdi/src/CMakeFiles/ftdi1-static.dir/build.make icsneo/third-party/libftdi/src/CMakeFiles/ftdi1-static.dir/build
.PHONY : ftdi1-static/fast

#=============================================================================
# Target rules for targets named ftdi1

# Build rule for target.
ftdi1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ftdi1
.PHONY : ftdi1

# fast build rule for target.
ftdi1/fast:
	$(MAKE) -f icsneo/third-party/libftdi/src/CMakeFiles/ftdi1.dir/build.make icsneo/third-party/libftdi/src/CMakeFiles/ftdi1.dir/build
.PHONY : ftdi1/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... advision"
	@echo "... vision"
	@echo "... icsneoc"
	@echo "... icsneocpp"
	@echo "... icsneolegacy"
	@echo "... dist"
	@echo "... ftdi1-static"
	@echo "... ftdi1"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

